FROM node:16 AS build

WORKDIR /opt/adme

COPY client ./

RUN npm install && npm install -g @angular/cli

# build parameter for opendata subdomain
RUN ng build --configuration production --deploy-url=/adme/client/ --base-href=/adme

FROM continuumio/miniconda:4.7.12

# Install NCATS required packages
RUN apt-get install -y net-tools

WORKDIR /opt/adme

COPY server ./

RUN conda env create -f environment.yml

ENV PATH /opt/conda/envs/ncats-adme/bin:$PATH

RUN chmod +x startup.sh

# clean existing client folder
RUN rm -rf client
COPY --from=build /opt/adme/dist/client client

CMD /bin/bash startup.sh

EXPOSE 5000
RUN echo "docker file done"
